### ISSUE TITLE
Adding Names Back

### ISSUE THREAD

**Issue by billyb2** [redcode-labs/Sammler#1]
Names are incredibly useful information to get from a document. I assumed you removed it since they are rather difficult to fit into a single regex expression, though wouldn't just iterating through a list of first and last names work as well? Obviously it's rather memory intensive, however I think that it at least providing it as an option would be useful. I could create a pull request that implements it, just want to know your thoughts first.

**Comment by unrooted** [comment]
Hey, it's a great idea! Feel free to do this, we're always open for any kind of contributions. But, when it comes to names and surnames, the only problem is that the Latin is not the only alphabet, so the possibilities of that would be limited (unless you implement other character sets). But still, this is a really useful input. Thanks for your issue!

**Comment by billyb2** [comment]
Hmm, very true. Maybe have the regular option of all possible names, and then the options of names using specific alphabets?

**Comment by wintrmvte** [comment]
Yeah, they will be probably included in a huge, single slice :>

**Comment by unrooted** [comment]
Done in ec3de9e7ab6d3e2e611d010cf792ee149d54e919
