### ISSUE TITLE
Cryptocurrencies Addresses/Keys

### ISSUE THREAD

**Issue by billyb2** [redcode-labs/Sammler#2]
Cryptocurrencies, while pseudononymous in principal, in practice are incredibly traceable (with notable exceptions being Monero, Zcash, and Grin). By finding public addresses (or keys), it makes tracing a person's financial history much easier, and even having someone's Monero public address, as an example, if posted on multiple places on the internet, can be useful in identifying a user.

**Comment by billyb2** [comment]
After a quick search on the internet, I found:
^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$

May be a suitable regex (I'm very bad at reading Regex though)
https://stackoverflow.com/questions/21683680/regex-to-match-bitcoin-addresses#24205650

(I apologize for making so many issues by the way, I like to separate different tasks out, and wasn't sure if you'd like it that way).

**Comment by wintrmvte** [comment]
No problem, splitting issues is imho always better than consolidating them. This regex looks solid, and we will include it in the next commit. Cheers, and thanks.

**Comment by billyb2** [comment]
Oh I apologize, upon some further inspection it doesn't include bech32 addresses. This should be more accurate:
^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$
https://ihateregex.io/expr/bitcoin-address/

**Comment by unrooted** [comment]
Done in 37861abcc86f33037449ba7344894d843769b313
