### ISSUE TITLE
No such directory: "/github.com/"

### ISSUE THREAD

**Issue by M3kat** [redcode-labs/Sammler#3]
kali@kali:~$ go run /home/kali/Sammler/sammler.go
Sammler/sammler.go:6:5: cannot find package "github.com/akamensky/argparse" in any of:
        /usr/lib/go/src/github.com/akamensky/argparse (from $GOROOT)
        /home/kali/go/src/github.com/akamensky/argparse (from $GOPATH)
Sammler/sammler.go:4:5: cannot find package "github.com/fatih/color" in any of:
        /usr/lib/go/src/github.com/fatih/color (from $GOROOT)
        /home/kali/go/src/github.com/fatih/color (from $GOPATH)

**Comment by wintrmvte** [comment]
Please install the missing packages
